deployment: deployment
environment:
  name: feature21
  dependencyenv: dev
  domainOverride:
    enabled: false
    domain: mycarrier.dev
applications:
  routetester:
    deploymentType: deployment
    replicas: 1
    ports:
      http: 8080
    networking:
      ingress:
        type: istio
    image:
      registry: example.com
      repository: foo
      tag: latest
    env: {}
    service:
      ports:
        - name: http
          port: 8080
          targetPort: 8080
global:
  appStack: devopptest
  language: python
