apiVersion: v2
name: mycarrier-helm
description: A Helm chart for MyCarrier GitOps
type: application
icon: https://go.mycarrier.io/hs-fs/hubfs/Logos/PNG-MC-COLOR-Logo.png?width=366&height=85&name=PNG-MC-COLOR-Logo.png
version: 3.0.35
appVersion: 3.0.29
