{{- if not .Values.mongodb.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongobetween.fullname" . }}-mongodb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mongobetween.labels" . | nindent 4 }}
type: Opaque
stringData:
  uri: {{ include "mongobetween.mongodbUri" . | quote }}
{{- end }}
